// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/screenshot/screenshot.proto

package screenshot

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ImageRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ImageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ImageRequestMultiError, or
// nil if none found.
func (m *ImageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if uri, err := url.Parse(m.GetUrl()); err != nil {
		err = ImageRequestValidationError{
			field:  "Url",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := ImageRequestValidationError{
			field:  "Url",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ImageRequest_Url_Pattern.MatchString(m.GetUrl()) {
		err := ImageRequestValidationError{
			field:  "Url",
			reason: "value does not match regex pattern \"^https?://\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ImageRequestMultiError(errors)
	}

	return nil
}

// ImageRequestMultiError is an error wrapping multiple validation errors
// returned by ImageRequest.ValidateAll() if the designated constraints aren't met.
type ImageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageRequestMultiError) AllErrors() []error { return m }

// ImageRequestValidationError is the validation error returned by
// ImageRequest.Validate if the designated constraints aren't met.
type ImageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageRequestValidationError) ErrorName() string { return "ImageRequestValidationError" }

// Error satisfies the builtin error interface
func (e ImageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageRequestValidationError{}

var _ImageRequest_Url_Pattern = regexp.MustCompile("^https?://")

// Validate checks the field values on ImageResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ImageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ImageResponseMultiError, or
// nil if none found.
func (m *ImageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Image

	if len(errors) > 0 {
		return ImageResponseMultiError(errors)
	}

	return nil
}

// ImageResponseMultiError is an error wrapping multiple validation errors
// returned by ImageResponse.ValidateAll() if the designated constraints
// aren't met.
type ImageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageResponseMultiError) AllErrors() []error { return m }

// ImageResponseValidationError is the validation error returned by
// ImageResponse.Validate if the designated constraints aren't met.
type ImageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageResponseValidationError) ErrorName() string { return "ImageResponseValidationError" }

// Error satisfies the builtin error interface
func (e ImageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageResponseValidationError{}
